# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-28 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcontent',
            name='urlconf_path',
            field=models.CharField(choices=[(b'blog.urls', b'Blog application')], max_length=100, verbose_name='application'),
        ),
    ]
