# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-29 01:33
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_indexpageinfoct'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpageinfoct',
            name='text_about_us',
            field=redactor.fields.RedactorField(blank=True, verbose_name='text_about_us'),
        ),
    ]
