# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-29 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_indexpageinfoct_text_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcontent',
            name='urlconf_path',
            field=models.CharField(choices=[(b'cases.urls', b'Cases category'), (b'blog.urls', b'Blog application')], max_length=100, verbose_name='application'),
        ),
    ]
