# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-16 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20171229_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='language',
            field=models.CharField(choices=[(b'ru', 'Russian'), (b'en', 'English'), (b'uk', 'Ukrainian')], default=b'ru', max_length=10, verbose_name='language'),
        ),
    ]
