# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-27 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_footer', models.CharField(max_length=255, verbose_name='adress')),
                ('email_footer', models.CharField(max_length=255, verbose_name='email')),
                ('phone_footer', models.CharField(max_length=255, verbose_name='phone_footer')),
                ('facebook_link', models.CharField(max_length=255, verbose_name='facebook_link')),
                ('insta_link', models.CharField(max_length=255, verbose_name='insta_link')),
                ('twitter_link', models.CharField(max_length=255, verbose_name='twitter_link')),
            ],
            options={
                'ordering': ['adress_footer'],
                'verbose_name': 'Info',
                'verbose_name_plural': 'Info',
            },
        ),
    ]
