# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-28 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='adress_footer_en',
            field=models.CharField(max_length=255, null=True, verbose_name='adress'),
        ),
        migrations.AddField(
            model_name='info',
            name='adress_footer_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='adress'),
        ),
        migrations.AddField(
            model_name='info',
            name='adress_footer_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='adress'),
        ),
    ]
