# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-21 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20171228_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='behance_link',
            field=models.CharField(default='', max_length=255, verbose_name='behance_link'),
            preserve_default=False,
        ),
    ]
