# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-21 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_info_behance_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='behance_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='behance_link'),
        ),
        migrations.AlterField(
            model_name='info',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='facebook_link'),
        ),
        migrations.AlterField(
            model_name='info',
            name='insta_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='insta_link'),
        ),
        migrations.AlterField(
            model_name='info',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='twitter_link'),
        ),
    ]
