# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-21 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20180121_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscriber',
            },
        ),
    ]
