# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-23 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='first_name')),
                ('second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='second_name')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('budget', models.CharField(blank=True, max_length=255, null=True, verbose_name='budget')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='company')),
                ('message', redactor.fields.RedactorField(blank=True, verbose_name='message')),
            ],
            options={
                'ordering': ['first_name'],
                'verbose_name': 'ContactInfo',
                'verbose_name_plural': 'ContactInfo',
            },
        ),
    ]
