# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-30 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='seo_description_blog',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='info',
            name='seo_description_blog_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='seo_description_blog_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='seo_description_blog_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='seo_keywords_blog',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='info',
            name='seo_keywords_blog_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='seo_keywords_blog_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='seo_keywords_blog_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='seo_title_blog',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='info',
            name='seo_title_blog_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='seo_title_blog_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='seo_title_blog_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
