# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-22 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_contactinfo_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_uk', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('position', models.CharField(max_length=255, verbose_name='position')),
                ('position_ru', models.CharField(max_length=255, null=True, verbose_name='position')),
                ('position_en', models.CharField(max_length=255, null=True, verbose_name='position')),
                ('position_uk', models.CharField(max_length=255, null=True, verbose_name='position')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'TeamMember',
                'verbose_name_plural': 'TeamMember',
            },
        ),
    ]
