# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-22 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_teammember_image_top'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='image_top',
            new_name='image',
        ),
    ]
