# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-27 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_preview', models.ImageField(upload_to=b'')),
                ('image_top', models.ImageField(upload_to=b'')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('author', models.CharField(max_length=255, null=True, verbose_name='author')),
                ('author_en', models.CharField(max_length=255, null=True, verbose_name='author')),
                ('author_ru', models.CharField(max_length=255, null=True, verbose_name='author')),
                ('author_uk', models.CharField(max_length=255, null=True, verbose_name='author')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='text')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='text')),
                ('text_uk', models.TextField(blank=True, null=True, verbose_name='text')),
                ('date', models.DateField(null=True, verbose_name='date')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-date',),
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
