# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-27 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-id',), 'verbose_name': 'Blog', 'verbose_name_plural': 'Blog'},
        ),
        migrations.AddField(
            model_name='blog',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='facebook_link'),
        ),
        migrations.AddField(
            model_name='blog',
            name='insta_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='insta_link'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tele_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='telegram_link'),
        ),
        migrations.AddField(
            model_name='blog',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='twitter_link'),
        ),
    ]
