# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-29 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171229_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitle_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_subtitle_tag', to='blog.BlogTag'),
        ),
    ]
