# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-10 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180109_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
