# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-16 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180110_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtag',
            options={'ordering': ('order',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
