# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-24 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180116_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='votes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
