# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-26 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180124_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subtitle_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='_subtitle_tag', to='blog.BlogTag'),
            preserve_default=False,
        ),
    ]
