# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-08 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180206_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtag',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='seo_description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='seo_description_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='seo_description_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='seo_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='seo_keywords_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='seo_keywords_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='seo_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
