# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-29 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_preview', models.ImageField(upload_to=b'')),
                ('image_top', models.ImageField(upload_to=b'')),
                ('activity_title', models.CharField(max_length=255, null=True, verbose_name='activity_title')),
                ('activity_title_en', models.CharField(max_length=255, null=True, verbose_name='activity_title')),
                ('activity_title_ru', models.CharField(max_length=255, null=True, verbose_name='activity_title')),
                ('activity_title_uk', models.CharField(max_length=255, null=True, verbose_name='activity_title')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('client', models.CharField(max_length=255, null=True, verbose_name='client')),
                ('client_en', models.CharField(max_length=255, null=True, verbose_name='client')),
                ('client_ru', models.CharField(max_length=255, null=True, verbose_name='client')),
                ('client_uk', models.CharField(max_length=255, null=True, verbose_name='client')),
                ('project', models.TextField(blank=True, null=True, verbose_name='project')),
                ('project_en', models.TextField(blank=True, null=True, verbose_name='project')),
                ('project_ru', models.TextField(blank=True, null=True, verbose_name='project')),
                ('project_uk', models.TextField(blank=True, null=True, verbose_name='project')),
                ('case_site', models.TextField(blank=True, null=True, verbose_name='case_site')),
                ('case_site_en', models.TextField(blank=True, null=True, verbose_name='case_site')),
                ('case_site_ru', models.TextField(blank=True, null=True, verbose_name='case_site')),
                ('case_site_uk', models.TextField(blank=True, null=True, verbose_name='case_site')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-id',),
                'verbose_name': 'Case',
                'verbose_name_plural': 'Case',
            },
        ),
        migrations.CreateModel(
            name='CaseService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_service_case', to='cases.Case')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'CaseService',
                'verbose_name_plural': 'CaseService',
            },
        ),
    ]
