# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-29 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20171229_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='case_site'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_site_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='case_site'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_site_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='case_site'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_site_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='case_site'),
        ),
    ]
