# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-29 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20171229_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='case',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='case',
            name='text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
    ]
