# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-29 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20171229_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='facebook_link'),
        ),
        migrations.AddField(
            model_name='case',
            name='insta_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='insta_link'),
        ),
        migrations.AddField(
            model_name='case',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='twitter_link'),
        ),
    ]
