# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-09 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20171229_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='seo_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
