# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-24 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20180110_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='behance_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='behance_link'),
        ),
        migrations.AlterField(
            model_name='case',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
